version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
