name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Python tests
      run: |
        pytest backend/tests

    - name: Build Docker image
      run: |
        docker build -t university-blockchain-tracker .

    - name: Deploy to Docker Swarm
      run: |
        docker swarm init || true
        docker stack deploy --compose-file docker-compose.yml university-blockchain-tracker
        docker service ls

  deploy-contracts:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run Hardhat tests
      run: |
        npx hardhat test

    - name: Deploy contracts
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      run: |
        npx hardhat run scripts/deploy.js --network rinkeby
