name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Compile contracts
      run: yarn hardhat compile

    - name: Run tests
      run: yarn hardhat test

    - name: Run coverage
      run: yarn hardhat coverage

    - name: Analyze contracts with Mythril
      run: ./analyze_contracts.sh

    - name: Load environment variables
      run: npx dotenv -e .env

    - name: Run Hardhat tests
      run: |
        npx hardhat test

    - name: Deploy contracts to localhost
      if: success()  # Only deploy if tests pass
      run:
        yarn hardhat node & yarn hardhat run scripts/deploy.js --network localhost

    - name: Deploy contracts to Rinkeby
      if: success()  # Only deploy if tests pass
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      run: |
        npx hardhat run scripts/deploy.js --network rinkeby

    - name: Send notification
      if: success()
      run: echo "Deployment successful!"

    - name: Notify failure
      if: failure()
      run: echo "Deployment failed!"
